name: CI
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Setup
        run: npm ci

      - name: Run tests
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
